Help kchecker and wine_checker.sh find the smatch binary
If you are calling it from the smatch_scripts directory then use the
development version.  If it is not in the smatch_scripts directory
hopefully you have done a "make install" and smatch is in your path.

Signed-off-by: Dan Carpenter <error27@gmail.com>

diff --git a/smatch_scripts/kchecker b/smatch_scripts/kchecker
--- a/smatch_scripts/kchecker
+++ b/smatch_scripts/kchecker
@@ -5,7 +5,16 @@ function useage {
     exit 1
 }
 
-CMD=smatch
+SCRIPT_DIR=$(dirname $0)
+if [ -e $SCRIPT_DIR/../smatch ] ; then
+    CMD=$SCRIPT_DIR/../smatch
+elif which smatch | grep smatch > /dev/null ; then
+    CMD=smatch
+else
+    echo "Smatch binary not found."
+    exit 1
+fi
+
 POST="--project=kernel"
 
 while true ; do
