testsuite: move up arg_file()
Signed-off-by: Luc Van Oostenryck <luc.vanoostenryck@gmail.com>

diff --git a/validation/test-suite b/validation/test-suite
--- a/validation/test-suite
+++ b/validation/test-suite
@@ -213,6 +213,23 @@ minmax_patterns()
 	return $?
 }
 
+##
+# arg_file(filename) - checks if filename exists
+arg_file()
+{
+	[ -z "$1" ] && {
+		do_usage
+		exit 1
+	}
+	[ -e "$1" ] || {
+		error "Can't open file $1"
+		exit 1
+	}
+	return 0
+}
+
+
+##
 do_usage()
 {
 echo "$prog_name - a tiny automatic testing script"
@@ -454,21 +471,6 @@ _EOF
 		fi
 	done
 	echo " */"
-	return 0
-}
-
-##
-# arg_file(filename) - checks if filename exists
-arg_file()
-{
-	[ -z "$1" ] && {
-		do_usage
-		exit 1
-	}
-	[ -e "$1" ] || {
-		error "Can't open file $1"
-		exit 1
-	}
 	return 0
 }
 
